name: Flask App 01

on:
   push:
     branches: [ main ]
   pull_request: [ main ]

jobs:
   build: 
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install depedencies
        run: |
          python3 -m pip3 install --upgrade pip3
          pip3 install -r requirments.txt;
