name: On Release - Sprint-00

on:
  push:
    branches: [ main ]


env:
  IMAGE_NAME: metasprint-api

jobs:
  docker-publish-sprint-00:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.DOCKER_SECRET }}
      - name: Build & Push - Sprint-00
        run: |

          docker build -f Dockerfile.sprint00 -t $IMAGE_NAME .

          # Login to Github docker registry
           echo "${{ secrets.DOCKER_SECRET }}" | docker login -u ${{ secrets.USERNAME }} --password-stdin

          # Compose proper Image ID
          #IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          #IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          #VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          #[[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
